services:
  web:
    build: .
    ports:
        - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - db-data:/var/lib/mysql
    ports:
        - 3307:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8005:80
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 1M
    depends_on:
      - db

volumes:
  db-data:
    name: "my-app-data"
